### ISSUE TITLE
感觉要CGColorSpaceRelease

### ISSUE THREAD

**Issue by PhilCai1993** [boycechang/BCColor#2]
UIImage+BCColor 里面`CGColorSpaceCreateDeviceRGB`, 是不是应该`CGColorSpaceRelease`

**Comment by boycechang** [comment]
感谢反馈。这里并不需要写 CGColorSpaceRelease
Apple 的文档 [Working with Cocoa Data Types](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/WorkingWithCocoaDataTypes.html) 已经解释了：

> Core Foundation objects returned from annotated APIs are automatically memory managed in Swift—you do not need to invoke the CFRetain, CFRelease, or CFAutorelease functions yourself. If you return Core Foundation objects from your own C functions and Objective-C methods, annotate them with either CF_RETURNS_RETAINED or CF_RETURNS_NOT_RETAINED.
> …
> When Swift imports APIs that have not been annotated, the compiler cannot automatically memory manage the returned Core Foundation objects. Swift wraps these returned Core Foundation objects in an Unmanaged<T> structure.

[相关的SO回答](http://stackoverflow.com/questions/24900595/swift-cgpathrelease-and-arc)

**Comment by PhilCai1993** [comment]
学习了
